version: '3.8'

services:
  mcp-client:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "3001:3001"  # MCP Server
    volumes:
      - .:/app
    expose:
      - "3001"  # MCP Server
      - "8501"  # Streamlit
    environment:
      - PYTHONPATH=/app
      - MCP_SERVER_PORT=3001
      - STREAMLIT_SERVER_PORT=8501
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - mcp-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    networks:
      - mcp-network

volumes:
  ollama_data:

networks:
  mcp-network:
    driver: bridge
